In [ ]:
#loading dataset in pandas dataframe

In [41]:
import pandas as pd

# here upload dataset
df = pd.read_csv("../data/Sample_Superstore_Full_Dataset.csv")
#why we used (../data) because .. "it takes one step backward to exit the notebooks folder ,"/" now look around the space
# data/ means go forward into the folder,Sample_Superstore_Full_Dataset.csv it opens the dataset file

print(f"Dataset Size: {df.shape}")# it tells about datasetsize means number of rows and columns present in the entire dataset
df.head()# it shows first 5 number of rows and columns

Dataset Size: (1000, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2024-10001,2024-11-23,2024-11-24,Standard Class,CUST-1001,Customer 1,Consumer,United States,San Diego,...,22280,West,PROD-2001,Furniture,Chairs,Chairs Product 1,714.90,2,0.0,103.84
1,2,CA-2024-10002,2024-04-29,2024-05-04,First Class,CUST-1002,Customer 2,Consumer,United States,Seattle,...,30926,South,PROD-2002,Technology,Phones,Phones Product 2,3585.78,9,0.3,-142.64
2,3,CA-2024-10003,2024-06-23,2024-06-26,First Class,CUST-1003,Customer 3,Consumer,United States,Houston,...,70217,East,PROD-2003,Office Supplies,Binders,Binders Product 3,481.87,2,0.2,131.91
3,4,CA-2024-10004,2024-07-12,2024-07-13,Standard Class,CUST-1004,Customer 4,Home Office,United States,Tacoma,...,39871,Central,PROD-2004,Technology,Copiers,Copiers Product 4,4429.55,6,0.1,896.04
4,5,CA-2024-10005,2024-02-10,2024-02-17,Second Class,CUST-1005,Customer 5,Home Office,United States,Houston,...,44993,East,PROD-2005,Office Supplies,Paper,Paper Product 5,2277.98,6,0.1,79.94

In [42]:
import os #here we are importing operating system
os.getcwd()# getcwd stands for "get current working directory" it asks python where is the exact folder you are sitting inside right now

'C:\\Users\\dhara\\apexplanet-data-analytics\\notebooks'

In [ ]:
here why we used ..means "takes one step backward  out of the current folder"(present we are in notebooks folder)
/ means look inside
data/ means "go forward into the folder named data
Sample_Superstore_Full_Dataset.csv means "open specific file."

In [43]:
df.tail() # here it shows last 5 number of rows and columns

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
995,996,CA-2024-10996,2024-10-15,2024-10-19,First Class,CUST-1996,Customer 996,Consumer,United States,Miami,...,36504,West,PROD-2996,Office Supplies,Binders,Binders Product 996,4844.03,6,0.1,1634.83
996,997,CA-2024-10997,2024-12-04,2024-12-10,Second Class,CUST-1997,Customer 997,Consumer,United States,Buffalo,...,90944,South,PROD-2997,Office Supplies,Binders,Binders Product 997,1622.79,7,0.2,209.40
997,998,CA-2024-10998,2024-05-20,2024-05-21,Standard Class,CUST-1998,Customer 998,Home Office,United States,Los Angeles,...,61126,South,PROD-2998,Furniture,Tables,Tables Product 998,3619.79,10,0.3,1180.13
998,999,CA-2024-10999,2024-05-07,2024-05-10,Same Day,CUST-1999,Customer 999,Corporate,United States,Tacoma,...,24553,South,PROD-2999,Furniture,Chairs,Chairs Product 999,299.45,6,0.2,35.62
999,1000,CA-2024-11000,2024-03-09,2024-03-15,Standard Class,CUST-2000,Customer 1000,Corporate,United States,San Diego,...,42142,Central,PROD-3000,Technology,Accessories,Accessories Product 1000,4125.07,3,0.2,565.32

In [44]:
df.info() #here it shows complete information about the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         1000 non-null   int64
 1   Order ID       1000 non-null   object
 2   Order Date     1000 non-null   object
 3   Ship Date      1000 non-null   object
 4   Ship Mode      1000 non-null   object
 5   Customer ID    1000 non-null   object
 6   Customer Name  1000 non-null   object
 7   Segment        1000 non-null   object
 8   Country        1000 non-null   object
 9   City           1000 non-null   object
 10  State          1000 non-null   object
 11  Postal Code    1000 non-null   int64
 12  Region         1000 non-null   object
 13  Product ID     1000 non-null   object
 14  Category       1000 non-null   object
 15  Sub-Category   1000 non-null   object
 16  Product Name   1000 non-null   object
 17  Sales          1000 non-null   float64
 18  Quantity       1000 non-null   int64
 19  Discount       1000 non-null   float64
 20  Profit         1000 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 164.2+ KB

In [45]:
df.describe() # it is used to show all the number of datasets in just one line

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,55228.068000,2585.802850,5.440000,0.152000,259.652810
std,288.819436,26153.465871,1430.994508,2.805043,0.112999,457.201169
min,1.000000,10150.000000,24.320000,1.000000,0.000000,-688.750000
25%,250.750000,31943.750000,1343.327500,3.000000,0.100000,-36.287500
50%,500.500000,54084.500000,2603.540000,5.000000,0.200000,153.745000
75%,750.250000,78363.750000,3778.222500,8.000000,0.300000,513.920000
max,1000.000000,99853.000000,4997.240000,10.000000,0.300000,1704.880000

In [46]:
df.columns #shows entire columns present in the dataset

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [47]:
# it shows entire rows and columns in the dataset
df.shape

(1000, 21)

In [48]:
df["Sales"]

0       714.90
1      3585.78
2       481.87
3      4429.55
4      2277.98
        ...
995    4844.03
996    1622.79
997    3619.79
998     299.45
999    4125.07
Name: Sales, Length: 1000, dtype: float64

In [49]:
df["Sales"].sum()

np.float64(2585802.85)

In [50]:
df["Profit"].sum()

np.float64(259652.81)

In [51]:
df["Sales"].mean()

np.float64(2585.80285)

In [52]:
df["Profit"].mean()

np.float64(259.65281)

In [53]:
df.groupby("Category")["Sales"].sum()

Category
Furniture           809125.55
Office Supplies     776296.76
Technology         1000380.54
Name: Sales, dtype: float64

In [54]:
df.groupby("Category")["Profit"].sum()

Category
Furniture          83746.05
Office Supplies    84739.96
Technology         91166.80
Name: Profit, dtype: float64

In [ ]:
# Step 2 : handle missing values(fill or drop)

In [55]:
#it scans every single cell in our huge data tables
#it repaces our actual data values with true or false words
# false means cell is not empty(it contain real data like a name,date,or numbers)
# true means the cell is blank or empty
df.isnull()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [56]:
#instead of reading 1000 rows,it gives us a clean checklist.if a column shows 0,it means it is fully complete
df.isnull().sum()#these are the empty cells present in each column

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [ ]:
# Step 3 : Removing Duplicates

In [57]:
#it goes to entire dataset,line by line
#it marks every row as false or (true)if it is unique 
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [58]:
print(df.duplicated().sum())#here we counted how many double rows are in the data

0

In [59]:
df.duplicated().sum()# why i used this because it counts all the true values from the previous step
#it shows 0 means superstore dataset is already clean and doesnt contain any repeated rows

np.int64(0)

In [60]:
#here it deletes any duplicate rows found.but we already got 0 ,it didnt need to remove anything
df=df.drop_duplicates()

In [61]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [ ]:
# Step 4 : Fix data types(dates,cetogories)

In [62]:
# here we are converting text format date into date format
df['Order Date'] = pd.to_datetime(df['Order Date'],format="mixed")
df['Ship Date'] = pd.to_datetime(df['Ship Date'],format="mixed")

In [63]:
print(df[["Order Date","Ship Date"]].dtypes)

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

In [64]:
print(df[['Order Date','Ship Date']].head())

  Order Date  Ship Date
0 2024-11-23 2024-11-24
1 2024-04-29 2024-05-04
2 2024-06-23 2024-06-26
3 2024-07-12 2024-07-13
4 2024-02-10 2024-02-17

In [ ]:
# now check the unique categories

In [65]:
df['Category'].unique()

array(['Furniture', 'Technology', 'Office Supplies'], dtype=object)

In [66]:
df['Segment'].unique()

array(['Consumer', 'Home Office', 'Corporate'], dtype=object)

In [67]:
df['Region'].unique()

array(['West', 'South', 'East', 'Central'], dtype=object)

In [ ]:
#Step 5 : Handle ouliers using IQR method

In [ ]:
# Outlier detection Q1(first quartile) and Q3(third quartile)
# q1 means 25% of data lies below 25
# q3 means 75% of data lies below 65

In [68]:
Q1 = df['Sales'].quantile(0.25)
Q3 = df['Sales'].quantile(0.75)

# Calculate IQR
IQR = Q3-Q1

lower= Q1-1.5*IQR
upper= Q3+1.5*IQR

In [69]:
outliers = df[(df['Sales']<lower)  | (df['Sales']>upper)]
print(outliers.shape)

(0, 21)

In [ ]:
#Step 6: Save cleaned dataset

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         1000 non-null   int64
 1   Order ID       1000 non-null   object
 2   Order Date     1000 non-null   datetime64[ns]
 3   Ship Date      1000 non-null   datetime64[ns]
 4   Ship Mode      1000 non-null   object
 5   Customer ID    1000 non-null   object
 6   Customer Name  1000 non-null   object
 7   Segment        1000 non-null   object
 8   Country        1000 non-null   object
 9   City           1000 non-null   object
 10  State          1000 non-null   object
 11  Postal Code    1000 non-null   int64
 12  Region         1000 non-null   object
 13  Product ID     1000 non-null   object
 14  Category       1000 non-null   object
 15  Sub-Category   1000 non-null   object
 16  Product Name   1000 non-null   object
 17  Sales          1000 non-null   float64
 18  Quantity       1000 non-null   int64
 19  Discount       1000 non-null   float64
 20  Profit         1000 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 164.2+ KB

In [71]:
df.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,1000.000000,1000,1000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,2024-06-30 09:41:45.600000,2024-07-04 10:06:14.399999744,55228.068000,2585.802850,5.440000,0.152000,259.652810
min,1.000000,2024-01-01 00:00:00,2024-01-02 00:00:00,10150.000000,24.320000,1.000000,0.000000,-688.750000
25%,250.750000,2024-04-03 18:00:00,2024-04-08 18:00:00,31943.750000,1343.327500,3.000000,0.100000,-36.287500
50%,500.500000,2024-06-28 00:00:00,2024-07-02 00:00:00,54084.500000,2603.540000,5.000000,0.200000,153.745000
75%,750.250000,2024-09-25 00:00:00,2024-09-28 00:00:00,78363.750000,3778.222500,8.000000,0.300000,513.920000
max,1000.000000,2024-12-31 00:00:00,2025-01-07 00:00:00,99853.000000,4997.240000,10.000000,0.300000,1704.880000
std,288.819436,NaN,NaN,26153.465871,1430.994508,2.805043,0.112999,457.201169

In [72]:
df.isnull()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [73]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [74]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [75]:
df.duplicated().sum()

np.int64(0)

In [76]:
df.to_csv("../data/cleaned_superstore.csv",index=False)