# SQL FUNDAMENTALS

here it creates csv file

and also it creates sqlite database which contains tables called sales

In [2]:
import pandas as pd
import sqlite3

# here we are loading dataset
df=pd.read_csv("../data/Sample_Superstore_Full_Dataset.csv")

# here we are creating database
conn= sqlite3.connect("superstore.db")

# here we are storing data in sql table
df.to_sql("sales",conn,
         if_exists="replace",index=False)

print("Database Created Successfully")

Database Created Successfully

In [3]:
# here it prints first 10 rows because we used  keyord called LIMIT 10 which only shows first 10 rows
query = "SELECT * FROM sales LIMIT 10"
pd.read_sql(query,conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2024-10001,2024-11-23,2024-11-24,Standard Class,CUST-1001,Customer 1,Consumer,United States,San Diego,...,22280,West,PROD-2001,Furniture,Chairs,Chairs Product 1,714.90,2,0.0,103.84
1,2,CA-2024-10002,2024-04-29,2024-05-04,First Class,CUST-1002,Customer 2,Consumer,United States,Seattle,...,30926,South,PROD-2002,Technology,Phones,Phones Product 2,3585.78,9,0.3,-142.64
2,3,CA-2024-10003,2024-06-23,2024-06-26,First Class,CUST-1003,Customer 3,Consumer,United States,Houston,...,70217,East,PROD-2003,Office Supplies,Binders,Binders Product 3,481.87,2,0.2,131.91
3,4,CA-2024-10004,2024-07-12,2024-07-13,Standard Class,CUST-1004,Customer 4,Home Office,United States,Tacoma,...,39871,Central,PROD-2004,Technology,Copiers,Copiers Product 4,4429.55,6,0.1,896.04
4,5,CA-2024-10005,2024-02-10,2024-02-17,Second Class,CUST-1005,Customer 5,Home Office,United States,Houston,...,44993,East,PROD-2005,Office Supplies,Paper,Paper Product 5,2277.98,6,0.1,79.94
5,6,CA-2024-10006,2024-11-07,2024-11-13,Standard Class,CUST-1006,Customer 6,Consumer,United States,Houston,...,14207,Central,PROD-2006,Furniture,Tables,Tables Product 6,1909.69,9,0.1,367.25
6,7,CA-2024-10007,2024-07-24,2024-07-27,Same Day,CUST-1007,Customer 7,Consumer,United States,Los Angeles,...,44718,West,PROD-2007,Technology,Copiers,Copiers Product 7,1587.10,8,0.3,463.98
7,8,CA-2024-10008,2024-05-06,2024-05-12,Second Class,CUST-1008,Customer 8,Home Office,United States,Tacoma,...,74686,East,PROD-2008,Technology,Copiers,Copiers Product 8,2153.60,10,0.3,66.76
8,9,CA-2024-10009,2024-01-25,2024-02-01,Same Day,CUST-1009,Customer 9,Home Office,United States,Los Angeles,...,42953,East,PROD-2009,Technology,Phones,Phones Product 9,3964.56,7,0.0,168.03
9,10,CA-2024-10010,2024-12-14,2024-12-20,First Class,CUST-1010,Customer 10,Home Office,United States,San Diego,...,33416,East,PROD-2010,Technology,Accessories,Accessories Product 10,575.53,7,0.1,44.24

# SQL QUERIES: SELECT

In [4]:
# Here it adds sum of the all sales values
query="""
SELECT SUM(Sales) AS Total_Sales
FROM sales
"""
result=pd.read_sql(query,conn)
result

   Total_Sales
0   2585802.85

In [5]:
# Here it shows average sales values
query="""
SELECT AVG(Sales) AS Average_Sales
FROM sales
"""
result=pd.read_sql(query,conn)
result

   Average_Sales
0     2585.80285

In [6]:
# Here it shows highest sale values which is present in the Sales column
query="""
SELECT MAX(Sales) AS HIghest_Sales
FROM sales
"""
result=pd.read_sql(query,conn)
result

   HIghest_Sales
0        4997.24

In [7]:
# Here it shows lowest sale value which is present in the Sales column
query="""
SELECT MIN(Sales) AS Lowest_Sales
FROM sales
"""
result=pd.read_sql(query,conn)
result

   Lowest_Sales
0         24.32

In [8]:
# Here it shows total sum of profit values which is present in the profit column
query="""
SELECT SUM(Profit) AS Total_Profit
FROM sales
"""
result=pd.read_sql(query,conn)
result

   Total_Profit
0     259652.81

In [9]:
# Here it shows average sum of profit value which is present in the profit column
query="""
SELECT AVG(Profit) AS Average_Profit
FROM sales
"""
result=pd.read_sql(query,conn)
result

   Average_Profit
0       259.65281

In [10]:
# Here it shows maximum profit value which is present in the profit column
query="""
SELECT MAX(Profit) AS Highest_Profit
FROM sales
"""
result=pd.read_sql(query,conn)
result

   Highest_Profit
0         1704.88

In [11]:
# Here it shows minimum profit value which is present in the profit column
query="""
SELECT MIN(Profit) AS LOwest_Profit
FROM sales
"""
result=pd.read_sql(query,conn)
result

   LOwest_Profit
0        -688.75

# WHERE

WHERE --> IT FILTERS ROWS IN A TABLE BEFORE GROUPING

In [12]:
# Here it shows entire ROWS AND COLUMNS but which only contain greater than 500 sales
query="""
SELECT *
FROM sales
WHERE Sales > 500
"""
pd.read_sql(query,conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2024-10001,2024-11-23,2024-11-24,Standard Class,CUST-1001,Customer 1,Consumer,United States,San Diego,...,22280,West,PROD-2001,Furniture,Chairs,Chairs Product 1,714.90,2,0.0,103.84
1,2,CA-2024-10002,2024-04-29,2024-05-04,First Class,CUST-1002,Customer 2,Consumer,United States,Seattle,...,30926,South,PROD-2002,Technology,Phones,Phones Product 2,3585.78,9,0.3,-142.64
2,4,CA-2024-10004,2024-07-12,2024-07-13,Standard Class,CUST-1004,Customer 4,Home Office,United States,Tacoma,...,39871,Central,PROD-2004,Technology,Copiers,Copiers Product 4,4429.55,6,0.1,896.04
3,5,CA-2024-10005,2024-02-10,2024-02-17,Second Class,CUST-1005,Customer 5,Home Office,United States,Houston,...,44993,East,PROD-2005,Office Supplies,Paper,Paper Product 5,2277.98,6,0.1,79.94
4,6,CA-2024-10006,2024-11-07,2024-11-13,Standard Class,CUST-1006,Customer 6,Consumer,United States,Houston,...,14207,Central,PROD-2006,Furniture,Tables,Tables Product 6,1909.69,9,0.1,367.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
907,995,CA-2024-10995,2024-05-17,2024-05-19,First Class,CUST-1995,Customer 995,Corporate,United States,Buffalo,...,50372,South,PROD-2995,Office Supplies,Paper,Paper Product 995,742.03,6,0.2,196.35
908,996,CA-2024-10996,2024-10-15,2024-10-19,First Class,CUST-1996,Customer 996,Consumer,United States,Miami,...,36504,West,PROD-2996,Office Supplies,Binders,Binders Product 996,4844.03,6,0.1,1634.83
909,997,CA-2024-10997,2024-12-04,2024-12-10,Second Class,CUST-1997,Customer 997,Consumer,United States,Buffalo,...,90944,South,PROD-2997,Office Supplies,Binders,Binders Product 997,1622.79,7,0.2,209.40
910,998,CA-2024-10998,2024-05-20,2024-05-21,Standard Class,CUST-1998,Customer 998,Home Office,United States,Los Angeles,...,61126,South,PROD-2998,Furniture,Tables,Tables Product 998,3619.79,10,0.3,1180.13
911,1000,CA-2024-11000,2024-03-09,2024-03-15,Standard Class,CUST-2000,Customer 1000,Corporate,United States,San Diego,...,42142,Central,PROD-3000,Technology,Accessories,Accessories Product 1000,4125.07,3,0.2,565.32

In [13]:
# Here it shows entire ROWS AND COLUMNS but which only contain less than 500 sales
query="""
SELECT *
FROM sales
WHERE Sales < 500
"""
pd.read_sql(query,conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,3,CA-2024-10003,2024-06-23,2024-06-26,First Class,CUST-1003,Customer 3,Consumer,United States,Houston,...,70217,East,PROD-2003,Office Supplies,Binders,Binders Product 3,481.87,2,0.2,131.91
1,12,CA-2024-10012,2024-06-06,2024-06-08,Second Class,CUST-1012,Customer 12,Consumer,United States,Los Angeles,...,96474,South,PROD-2012,Technology,Phones,Phones Product 12,446.55,8,0.0,151.38
2,20,CA-2024-10020,2024-09-14,2024-09-21,Second Class,CUST-1020,Customer 20,Corporate,United States,Seattle,...,25713,West,PROD-2020,Furniture,Bookcases,Bookcases Product 20,418.96,3,0.0,61.80
3,78,CA-2024-10078,2024-07-14,2024-07-19,Standard Class,CUST-1078,Customer 78,Home Office,United States,Buffalo,...,75107,Central,PROD-2078,Technology,Accessories,Accessories Product 78,129.26,7,0.2,-18.87
4,91,CA-2024-10091,2024-08-06,2024-08-12,Standard Class,CUST-1091,Customer 91,Consumer,United States,San Diego,...,46046,Central,PROD-2091,Technology,Accessories,Accessories Product 91,385.98,2,0.2,59.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,915,CA-2024-10915,2024-11-25,2024-11-28,Same Day,CUST-1915,Customer 915,Home Office,United States,New York City,...,42763,East,PROD-2915,Technology,Phones,Phones Product 915,495.04,3,0.1,139.81
84,974,CA-2024-10974,2024-03-30,2024-04-03,Same Day,CUST-1974,Customer 974,Consumer,United States,Dallas,...,99610,South,PROD-2974,Furniture,Tables,Tables Product 974,342.77,1,0.1,47.58
85,982,CA-2024-10982,2024-01-15,2024-01-22,Second Class,CUST-1982,Customer 982,Corporate,United States,Dallas,...,94390,West,PROD-2982,Furniture,Bookcases,Bookcases Product 982,80.09,6,0.3,7.09
86,992,CA-2024-10992,2024-06-12,2024-06-17,Same Day,CUST-1992,Customer 992,Corporate,United States,Orlando,...,93608,West,PROD-2992,Furniture,Chairs,Chairs Product 992,346.49,7,0.2,-35.59
87,999,CA-2024-10999,2024-05-07,2024-05-10,Same Day,CUST-1999,Customer 999,Corporate,United States,Tacoma,...,24553,South,PROD-2999,Furniture,Chairs,Chairs Product 999,299.45,6,0.2,35.62

HERE WHY I USED ONLY 4 COLUMNS BECAUSE IT LOOKS SIMPLE AND EASY TO UNDERSTAND

In [14]:
# Here it only shows 4 columns state(California),city,sales and profit but which only contains sales which have sold more than 500
query="""
SELECT State,City, Sales,Profit
FROM sales
WHERE State = 'California'
AND Sales > 500
"""
pd.read_sql(query,conn)

          State         City    Sales   Profit
0    California    San Diego   714.90   103.84
1    California  Los Angeles  1587.10   463.98
2    California  Los Angeles  3964.56   168.03
3    California    San Diego   575.53    44.24
4    California    San Diego  2067.29  -247.44
..          ...          ...      ...      ...
189  California    San Diego  3767.46    -8.87
190  California    San Diego  1048.02   161.73
191  California  Los Angeles  2518.86  -248.21
192  California  Los Angeles  3619.79  1180.13
193  California    San Diego  4125.07   565.32

[194 rows x 4 columns]

In [15]:
# Here it only shows 4 columns state(California),city,sales and profit but which only contains sales which have sold less than 500
query="""
SELECT State,City, Sales,Profit
FROM sales
WHERE State = 'California'
AND Sales < 500
"""
pd.read_sql(query,conn)

         State         City   Sales  Profit
0   California  Los Angeles  446.55  151.38
1   California    San Diego  385.98   59.50
2   California    San Diego  207.28  -23.14
3   California    San Diego  490.64  -11.78
4   California  Los Angeles  236.80   -5.49
5   California  Los Angeles  100.78   -0.24
6   California  Los Angeles  198.44   52.18
7   California  Los Angeles  175.35   41.14
8   California    San Diego  233.19   10.27
9   California    San Diego  356.42   89.13
10  California  Los Angeles  475.18  149.88
11  California    San Diego   42.76   -3.90
12  California  Los Angeles  210.64  -10.89
13  California    San Diego  442.02   24.47
14  California  Los Angeles  123.17  -10.34
15  California    San Diego  169.29   -3.31
16  California    San Diego  445.97    8.37

In [16]:
# Here it only shows 4 columns state(California),city,sales and profit but which only contains profit which have more than 500
query="""
SELECT State,City, Sales,Profit
FROM sales
WHERE State = 'California'
AND Profit > 500
"""
pd.read_sql(query,conn)

         State         City    Sales   Profit
0   California  Los Angeles  2926.69   928.79
1   California    San Diego  4899.39   616.54
2   California    San Diego  4869.71  1374.73
3   California  Los Angeles  3257.72  1058.13
4   California  Los Angeles  4850.38  1167.79
5   California    San Diego  2692.13   501.85
6   California    San Diego  4039.96   624.16
7   California    San Diego  4607.39   629.83
8   California    San Diego  3599.97   844.49
9   California  Los Angeles  4323.54  1432.57
10  California    San Diego  4313.75  1219.26
11  California    San Diego  4614.44   758.08
12  California    San Diego  4985.86  1269.65
13  California  Los Angeles  4587.78  1515.25
14  California    San Diego  4391.91   779.10
15  California  Los Angeles  4568.90  1049.69
16  California  Los Angeles  3726.17   909.35
17  California  Los Angeles  3351.73   803.62
18  California  Los Angeles  3243.05   964.04
19  California  Los Angeles  4395.61   982.18
20  California  Los Angeles  2799.26   855.16
21  California    San Diego  2683.48   611.78
22  California    San Diego  4692.45  1159.62
23  California  Los Angeles  4107.35  1152.62
24  California  Los Angeles  3824.01  1139.56
25  California  Los Angeles  2454.70   745.22
26  California    San Diego  3063.90   793.24
27  California  Los Angeles  3230.47   574.64
28  California  Los Angeles  2946.26   545.94
29  California    San Diego  4338.52   806.25
30  California    San Diego  4371.00   888.20
31  California  Los Angeles  2892.74   651.67
32  California  Los Angeles  4044.13  1092.94
33  California    San Diego  4718.87  1095.01
34  California  Los Angeles  4886.67  1661.89
35  California  Los Angeles  3406.20  1121.91
36  California    San Diego  2939.08   846.46
37  California  Los Angeles  4732.15   849.79
38  California    San Diego  4861.65  1571.35
39  California    San Diego  3071.50   612.25
40  California  Los Angeles  4501.35   823.82
41  California    San Diego  3459.15   761.83
42  California  Los Angeles  4468.59   599.45
43  California    San Diego  4710.19  1017.61
44  California    San Diego  4419.05  1387.32
45  California  Los Angeles  3613.54  1201.79
46  California    San Diego  2463.97   765.28
47  California    San Diego  4313.60  1418.26
48  California    San Diego  3848.43   801.68
49  California  Los Angeles  3619.79  1180.13
50  California    San Diego  4125.07   565.32

In [17]:
# Here it only shows 4 columns state(California),city,sales and profit but which only contains profit which have less than 500
query="""
SELECT State,City, Sales,Profit
FROM sales
WHERE State = 'California'
AND Profit < 500
"""
pd.read_sql(query,conn)

          State         City    Sales  Profit
0    California    San Diego   714.90  103.84
1    California  Los Angeles  1587.10  463.98
2    California  Los Angeles  3964.56  168.03
3    California    San Diego   575.53   44.24
4    California  Los Angeles   446.55  151.38
..          ...          ...      ...     ...
155  California    San Diego  3909.40 -368.12
156  California    San Diego  1438.86  -66.81
157  California    San Diego  3767.46   -8.87
158  California    San Diego  1048.02  161.73
159  California  Los Angeles  2518.86 -248.21

[160 rows x 4 columns]

In [18]:
# Here it only shows category(technology), 4 columns state,city,sales and profit but which only contains sales which have more than 500
query="""
SELECT State,City, Sales,Profit
FROM sales
WHERE Category = 'Technology'
AND Sales > 500
"""
pd.read_sql(query,conn)

          State         City    Sales  Profit
0    Washington      Seattle  3585.78 -142.64
1    Washington       Tacoma  4429.55  896.04
2    California  Los Angeles  1587.10  463.98
3    Washington       Tacoma  2153.60   66.76
4    California  Los Angeles  3964.56  168.03
..          ...          ...      ...     ...
343  Washington       Tacoma  1902.33  542.91
344  Washington      Seattle  4492.71  818.22
345       Texas      Houston  2396.87   22.60
346    New York      Buffalo  1718.89  280.11
347  California    San Diego  4125.07  565.32

[348 rows x 4 columns]

In [19]:
# Here it only shows category(technology), 4 columns state,city,sales and profit but which only contains sales which have less than 500
query="""
SELECT State,City, Sales,Profit
FROM sales
WHERE Category = 'Technology'
AND Sales < 500
"""
pd.read_sql(query,conn)

         State           City   Sales  Profit
0   California    Los Angeles  446.55  151.38
1     New York        Buffalo  129.26  -18.87
2   California      San Diego  385.98   59.50
3        Texas         Dallas  458.89   31.13
4   Washington        Seattle  237.59   79.54
5   California    Los Angeles  100.78   -0.24
6        Texas        Houston   65.52    2.40
7      Florida        Orlando  248.80  -21.86
8      Florida          Miami  330.17   -1.37
9     New York        Buffalo   56.59   -0.04
10       Texas         Dallas   63.84   -1.90
11  California    Los Angeles  175.35   41.14
12  Washington        Seattle  298.44   32.33
13  Washington         Tacoma  306.17   21.27
14    New York        Buffalo  457.22   26.82
15       Texas         Dallas  470.40  -28.28
16       Texas        Houston   80.79    9.84
17       Texas        Houston  202.87    3.16
18     Florida          Miami   24.32   -0.41
19       Texas         Dallas   35.32    0.24
20     Florida        Orlando   35.58    5.94
21    New York  New York City  401.93  -27.11
22    New York  New York City  304.15  -22.12
23     Florida        Orlando   38.31    6.40
24  California      San Diego  445.97    8.37
25    New York  New York City  387.29  118.25
26     Florida          Miami  213.29   35.30
27    New York  New York City  495.04  139.81

In [20]:
# Here it only shows category(technology), 4 columns state,city,sales and profit but which only contains profit which have more than 500
query="""
SELECT State,City, Sales,Profit
FROM sales
WHERE Category = 'Technology'
AND Profit > 500
"""
pd.read_sql(query,conn)

         State           City    Sales   Profit
0   Washington         Tacoma  4429.55   896.04
1   California      San Diego  4869.71  1374.73
2      Florida          Miami  3438.53   878.79
3      Florida          Miami  2263.56   633.99
4      Florida        Orlando  4106.34  1103.53
..         ...            ...      ...      ...
88  California      San Diego  4313.60  1418.26
89    New York  New York City  1844.99   565.47
90  Washington         Tacoma  1902.33   542.91
91  Washington        Seattle  4492.71   818.22
92  California      San Diego  4125.07   565.32

[93 rows x 4 columns]

In [21]:
# Here it only shows category(technology), 4 columns state,city,sales and profit but which only contains profit which have less than 500
query="""
SELECT State,City, Sales,Profit
FROM sales
WHERE Category = 'Technology'
AND Profit < 500
"""
pd.read_sql(query,conn)

          State         City    Sales  Profit
0    Washington      Seattle  3585.78 -142.64
1    California  Los Angeles  1587.10  463.98
2    Washington       Tacoma  2153.60   66.76
3    California  Los Angeles  3964.56  168.03
4    California    San Diego   575.53   44.24
..          ...          ...      ...     ...
278       Texas       Dallas   573.56  164.06
279  California    San Diego  3767.46   -8.87
280    New York      Buffalo  3372.93 -258.83
281       Texas      Houston  2396.87   22.60
282    New York      Buffalo  1718.89  280.11

[283 rows x 4 columns]

# ORDER BY and LIMIT

Q. WHY WE USE ORDER BY

A. ORDER BY IS USED TO SORT DATA IN A SPECIFIC ORDER.

   WITHOUT ORDER BY,SQL SHOWS ROWS IN ANY ORDER.WITH ORDER YOU CAN ARRANGE DATA FROM ASC OR DESC

   ASC--> ASCENDING ORDER, DESC--> DESCENDING ORDER

In [22]:
# Here it shows table in descending order which we assigned sales column
query = """
SELECT * 
FROM sales
ORDER BY Sales DESC
"""
pd.read_sql(query,conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,695,CA-2024-10695,2024-11-05,2024-11-09,Same Day,CUST-1695,Customer 695,Home Office,United States,Buffalo,...,17502,Central,PROD-2695,Technology,Accessories,Accessories Product 695,4997.24,4,0.2,912.19
1,495,CA-2024-10495,2024-04-21,2024-04-23,Second Class,CUST-1495,Customer 495,Home Office,United States,Buffalo,...,70199,East,PROD-2495,Furniture,Bookcases,Bookcases Product 495,4994.78,1,0.3,921.63
2,279,CA-2024-10279,2024-12-04,2024-12-07,Standard Class,CUST-1279,Customer 279,Home Office,United States,Houston,...,84978,West,PROD-2279,Technology,Accessories,Accessories Product 279,4987.40,5,0.3,260.84
3,932,CA-2024-10932,2024-11-16,2024-11-17,Standard Class,CUST-1932,Customer 932,Consumer,United States,Seattle,...,58435,East,PROD-2932,Technology,Accessories,Accessories Product 932,4986.21,8,0.3,-314.70
4,244,CA-2024-10244,2024-07-09,2024-07-15,Standard Class,CUST-1244,Customer 244,Corporate,United States,San Diego,...,26059,East,PROD-2244,Furniture,Chairs,Chairs Product 244,4985.86,4,0.3,1269.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,790,CA-2024-10790,2024-02-28,2024-03-06,Standard Class,CUST-1790,Customer 790,Consumer,United States,Orlando,...,38655,West,PROD-2790,Technology,Copiers,Copiers Product 790,38.31,8,0.1,6.40
996,697,CA-2024-10697,2024-08-19,2024-08-24,Standard Class,CUST-1697,Customer 697,Home Office,United States,Orlando,...,52667,South,PROD-2697,Technology,Phones,Phones Product 697,35.58,6,0.0,5.94
997,558,CA-2024-10558,2024-11-24,2024-11-30,Standard Class,CUST-1558,Customer 558,Consumer,United States,Dallas,...,30686,West,PROD-2558,Technology,Phones,Phones Product 558,35.32,4,0.2,0.24
998,690,CA-2024-10690,2024-07-22,2024-07-28,First Class,CUST-1690,Customer 690,Home Office,United States,New York City,...,66485,West,PROD-2690,Furniture,Tables,Tables Product 690,27.86,2,0.3,3.13
999,473,CA-2024-10473,2024-08-16,2024-08-17,First Class,CUST-1473,Customer 473,Corporate,United States,Miami,...,85319,East,PROD-2473,Technology,Copiers,Copiers Product 473,24.32,1,0.3,-0.41

In [23]:
# Here it shows table in ascending order which we assigned sales column
query = """
SELECT * 
FROM sales
ORDER BY Sales ASC
"""
pd.read_sql(query,conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,473,CA-2024-10473,2024-08-16,2024-08-17,First Class,CUST-1473,Customer 473,Corporate,United States,Miami,...,85319,East,PROD-2473,Technology,Copiers,Copiers Product 473,24.32,1,0.3,-0.41
1,690,CA-2024-10690,2024-07-22,2024-07-28,First Class,CUST-1690,Customer 690,Home Office,United States,New York City,...,66485,West,PROD-2690,Furniture,Tables,Tables Product 690,27.86,2,0.3,3.13
2,558,CA-2024-10558,2024-11-24,2024-11-30,Standard Class,CUST-1558,Customer 558,Consumer,United States,Dallas,...,30686,West,PROD-2558,Technology,Phones,Phones Product 558,35.32,4,0.2,0.24
3,697,CA-2024-10697,2024-08-19,2024-08-24,Standard Class,CUST-1697,Customer 697,Home Office,United States,Orlando,...,52667,South,PROD-2697,Technology,Phones,Phones Product 697,35.58,6,0.0,5.94
4,790,CA-2024-10790,2024-02-28,2024-03-06,Standard Class,CUST-1790,Customer 790,Consumer,United States,Orlando,...,38655,West,PROD-2790,Technology,Copiers,Copiers Product 790,38.31,8,0.1,6.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,244,CA-2024-10244,2024-07-09,2024-07-15,Standard Class,CUST-1244,Customer 244,Corporate,United States,San Diego,...,26059,East,PROD-2244,Furniture,Chairs,Chairs Product 244,4985.86,4,0.3,1269.65
996,932,CA-2024-10932,2024-11-16,2024-11-17,Standard Class,CUST-1932,Customer 932,Consumer,United States,Seattle,...,58435,East,PROD-2932,Technology,Accessories,Accessories Product 932,4986.21,8,0.3,-314.70
997,279,CA-2024-10279,2024-12-04,2024-12-07,Standard Class,CUST-1279,Customer 279,Home Office,United States,Houston,...,84978,West,PROD-2279,Technology,Accessories,Accessories Product 279,4987.40,5,0.3,260.84
998,495,CA-2024-10495,2024-04-21,2024-04-23,Second Class,CUST-1495,Customer 495,Home Office,United States,Buffalo,...,70199,East,PROD-2495,Furniture,Bookcases,Bookcases Product 495,4994.78,1,0.3,921.63
999,695,CA-2024-10695,2024-11-05,2024-11-09,Same Day,CUST-1695,Customer 695,Home Office,United States,Buffalo,...,17502,Central,PROD-2695,Technology,Accessories,Accessories Product 695,4997.24,4,0.2,912.19

In [24]:
# Here it only shows columns state(California),city,sales,profit which have sold less than 500 in desc order
query="""
SELECT State,City, Sales,Profit
FROM sales
WHERE State = 'California'
AND Sales < 500
ORDER BY Sales DESC
"""
pd.read_sql(query,conn)

         State         City   Sales  Profit
0   California    San Diego  490.64  -11.78
1   California  Los Angeles  475.18  149.88
2   California  Los Angeles  446.55  151.38
3   California    San Diego  445.97    8.37
4   California    San Diego  442.02   24.47
5   California    San Diego  385.98   59.50
6   California    San Diego  356.42   89.13
7   California  Los Angeles  236.80   -5.49
8   California    San Diego  233.19   10.27
9   California  Los Angeles  210.64  -10.89
10  California    San Diego  207.28  -23.14
11  California  Los Angeles  198.44   52.18
12  California  Los Angeles  175.35   41.14
13  California    San Diego  169.29   -3.31
14  California  Los Angeles  123.17  -10.34
15  California  Los Angeles  100.78   -0.24
16  California    San Diego   42.76   -3.90

In [25]:
# Here it only shows columns state,city,sales,profit which only targeting sales column in desc order
query="""
SELECT State,City, Sales,Category,Profit
FROM sales
ORDER BY Sales DESC
LIMIT 10
"""
pd.read_sql(query,conn)

        State         City    Sales    Category   Profit
0    New York      Buffalo  4997.24  Technology   912.19
1    New York      Buffalo  4994.78   Furniture   921.63
2       Texas      Houston  4987.40  Technology   260.84
3  Washington      Seattle  4986.21  Technology  -314.70
4  California    San Diego  4985.86   Furniture  1269.65
5  Washington      Seattle  4985.45  Technology  -143.79
6    New York      Buffalo  4985.14   Furniture   584.82
7  California  Los Angeles  4981.99   Furniture   221.12
8       Texas       Dallas  4981.01  Technology   558.82
9     Florida        Miami  4961.89   Furniture  1704.88

In [26]:
# Here it only shows columns state,city,sales,category,profit which only targeting profit column in desc order
query="""
SELECT State,City, Sales,Category,Profit
FROM sales
ORDER BY Profit DESC
LIMIT 10
"""
pd.read_sql(query,conn)

        State         City    Sales         Category   Profit
0     Florida        Miami  4961.89        Furniture  1704.88
1  California  Los Angeles  4886.67        Furniture  1661.89
2     Florida        Miami  4901.78        Furniture  1641.43
3     Florida        Miami  4816.32  Office Supplies  1636.04
4     Florida        Miami  4844.03  Office Supplies  1634.83
5  Washington      Seattle  4656.70        Furniture  1622.25
6  California    San Diego  4861.65       Technology  1571.35
7     Florida      Orlando  4640.50        Furniture  1554.92
8     Florida        Miami  4565.29       Technology  1541.49
9     Florida      Orlando  4760.17  Office Supplies  1532.16

In [27]:
# Here it only shows columns state,city,sales,category,profit which only targeting profit column in asc order
query="""
SELECT State,City, Sales,Category,Profit
FROM sales
ORDER BY Profit ASC
LIMIT 10
"""
pd.read_sql(query,conn)

        State           City    Sales         Category  Profit
0     Florida          Miami  4735.85       Technology -688.75
1  California      San Diego  4784.38  Office Supplies -686.64
2  Washington        Seattle  4490.06        Furniture -661.56
3  Washington         Tacoma  4504.21        Furniture -661.27
4  Washington         Tacoma  4400.54        Furniture -644.19
5    New York  New York City  4674.22       Technology -626.97
6     Florida        Orlando  4223.36  Office Supplies -626.52
7    New York  New York City  4383.46        Furniture -621.16
8  California    Los Angeles  4448.15  Office Supplies -617.22
9     Florida          Miami  4905.02  Office Supplies -587.25

In [28]:
query="""
SELECT *
FROM sales
ORDER BY State ASC
LIMIT 10
"""
pd.read_sql(query,conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2024-10001,2024-11-23,2024-11-24,Standard Class,CUST-1001,Customer 1,Consumer,United States,San Diego,...,22280,West,PROD-2001,Furniture,Chairs,Chairs Product 1,714.90,2,0.0,103.84
1,7,CA-2024-10007,2024-07-24,2024-07-27,Same Day,CUST-1007,Customer 7,Consumer,United States,Los Angeles,...,44718,West,PROD-2007,Technology,Copiers,Copiers Product 7,1587.10,8,0.3,463.98
2,9,CA-2024-10009,2024-01-25,2024-02-01,Same Day,CUST-1009,Customer 9,Home Office,United States,Los Angeles,...,42953,East,PROD-2009,Technology,Phones,Phones Product 9,3964.56,7,0.0,168.03
3,10,CA-2024-10010,2024-12-14,2024-12-20,First Class,CUST-1010,Customer 10,Home Office,United States,San Diego,...,33416,East,PROD-2010,Technology,Accessories,Accessories Product 10,575.53,7,0.1,44.24
4,12,CA-2024-10012,2024-06-06,2024-06-08,Second Class,CUST-1012,Customer 12,Consumer,United States,Los Angeles,...,96474,South,PROD-2012,Technology,Phones,Phones Product 12,446.55,8,0.0,151.38
5,16,CA-2024-10016,2024-04-07,2024-04-08,First Class,CUST-1016,Customer 16,Consumer,United States,San Diego,...,42591,West,PROD-2016,Office Supplies,Paper,Paper Product 16,2067.29,1,0.0,-247.44
6,21,CA-2024-10021,2024-10-23,2024-10-28,Second Class,CUST-1021,Customer 21,Home Office,United States,Los Angeles,...,51180,West,PROD-2021,Office Supplies,Storage,Storage Product 21,2926.69,9,0.2,928.79
7,26,CA-2024-10026,2024-05-21,2024-05-22,Same Day,CUST-1026,Customer 26,Home Office,United States,San Diego,...,11267,East,PROD-2026,Furniture,Bookcases,Bookcases Product 26,4899.39,3,0.3,616.54
8,28,CA-2024-10028,2024-12-15,2024-12-17,Second Class,CUST-1028,Customer 28,Corporate,United States,San Diego,...,13248,West,PROD-2028,Technology,Accessories,Accessories Product 28,4869.71,3,0.1,1374.73
9,33,CA-2024-10033,2024-07-05,2024-07-09,Same Day,CUST-1033,Customer 33,Corporate,United States,San Diego,...,62743,Central,PROD-2033,Technology,Accessories,Accessories Product 33,3323.67,2,0.2,344.20

In [29]:
query="""
SELECT *
FROM sales
ORDER BY Category ASC, Sales DESC
LIMIT 10
"""
pd.read_sql(query,conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,495,CA-2024-10495,2024-04-21,2024-04-23,Second Class,CUST-1495,Customer 495,Home Office,United States,Buffalo,...,70199,East,PROD-2495,Furniture,Bookcases,Bookcases Product 495,4994.78,1,0.3,921.63
1,244,CA-2024-10244,2024-07-09,2024-07-15,Standard Class,CUST-1244,Customer 244,Corporate,United States,San Diego,...,26059,East,PROD-2244,Furniture,Chairs,Chairs Product 244,4985.86,4,0.3,1269.65
2,475,CA-2024-10475,2024-06-19,2024-06-25,First Class,CUST-1475,Customer 475,Consumer,United States,Buffalo,...,70245,Central,PROD-2475,Furniture,Bookcases,Bookcases Product 475,4985.14,2,0.2,584.82
3,477,CA-2024-10477,2024-04-07,2024-04-09,First Class,CUST-1477,Customer 477,Corporate,United States,Los Angeles,...,79984,South,PROD-2477,Furniture,Bookcases,Bookcases Product 477,4981.99,4,0.3,221.12
4,283,CA-2024-10283,2024-09-28,2024-10-01,Same Day,CUST-1283,Customer 283,Consumer,United States,Miami,...,51469,West,PROD-2283,Furniture,Chairs,Chairs Product 283,4961.89,6,0.3,1704.88
5,626,CA-2024-10626,2024-09-09,2024-09-15,Same Day,CUST-1626,Customer 626,Consumer,United States,Seattle,...,82323,West,PROD-2626,Furniture,Chairs,Chairs Product 626,4921.63,7,0.0,1402.46
6,711,CA-2024-10711,2024-02-19,2024-02-22,Same Day,CUST-1711,Customer 711,Consumer,United States,Miami,...,14455,East,PROD-2711,Furniture,Chairs,Chairs Product 711,4901.78,6,0.3,1641.43
7,26,CA-2024-10026,2024-05-21,2024-05-22,Same Day,CUST-1026,Customer 26,Home Office,United States,San Diego,...,11267,East,PROD-2026,Furniture,Bookcases,Bookcases Product 26,4899.39,3,0.3,616.54
8,657,CA-2024-10657,2024-06-15,2024-06-20,Second Class,CUST-1657,Customer 657,Corporate,United States,Los Angeles,...,18350,South,PROD-2657,Furniture,Chairs,Chairs Product 657,4886.67,6,0.3,1661.89
9,320,CA-2024-10320,2024-11-29,2024-12-01,Second Class,CUST-1320,Customer 320,Home Office,United States,New York City,...,92511,West,PROD-2320,Furniture,Chairs,Chairs Product 320,4858.71,9,0.0,794.24

# GROUP BY

Q. WHY WE USE GROUP BY

A. GROUP BY IS USED TO COMBINE ROWS THAT HAVE THE SAME VALUE AND THEN PERFORM CALCULATIONS LIKE SUM(),AVG(),COUNT(),MAX(),MIN() IN EACH GROUP

In [30]:
# Here by using GROUP BY it shows total sales for each category
query="""
SELECT Category,
SUM(Sales) AS TotalSales
FROM sales
GROUP BY Category
"""
pd.read_sql(query,conn)

          Category  TotalSales
0        Furniture   809125.55
1  Office Supplies   776296.76
2       Technology  1000380.54

In [31]:
# Here by using GROUP BY it shows total profits for each category
query="""
SELECT Category,
SUM(Profit) AS TotalProfit
FROM sales
GROUP BY Category
"""
pd.read_sql(query,conn)

          Category  TotalProfit
0        Furniture     83746.05
1  Office Supplies     84739.96
2       Technology     91166.80

In [32]:
# Here by using GROUP BY it shows total sales for each state by using desc order
query="""
SELECT State,
SUM(Sales) AS TotalSales
FROM sales
GROUP BY State
ORDER BY TotalSales DESC
"""
pd.read_sql(query,conn)

        State  TotalSales
0  California   564487.72
1  Washington   526846.99
2     Florida   517151.60
3    New York   499426.19
4       Texas   477890.35

In [33]:
# Here by using GROUP BY it shows total profits for each state by using desc order
query="""
SELECT State,
SUM(Profit) AS TotalProfit
FROM sales
GROUP BY State
ORDER BY TotalProfit DESC
"""
pd.read_sql(query,conn)

        State  TotalProfit
0       Texas     55224.27
1     Florida     54694.08
2  California     51912.27
3  Washington     50686.54
4    New York     47135.65

# HAVING

Q. WHY WE USE HAVING

A. HAVING IS USED TO FILTER GROUPED DATA AFTER USING GROUP BY

# HERE WE ARE GONNA CHECK ABOUT CATEGORIES WITH TOTAL SALES>100000

In [34]:
query = """
SELECT Category,
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Category
HAVING SUM(Sales) > 100000
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0        Furniture    809125.55
1  Office Supplies    776296.76
2       Technology   1000380.54

STATE WHICH HAVING TOTAL PROFIT WHICH IS GRAETER THAN 5000

In [35]:
query = """
SELECT State,
SUM(Profit) AS Total_Profit
FROM sales
GROUP BY State
HAVING SUM(Profit) > 5000
"""

pd.read_sql(query, conn)

        State  Total_Profit
0  California      51912.27
1     Florida      54694.08
2    New York      47135.65
3       Texas      55224.27
4  Washington      50686.54

HERE WE CAN SEE CATEGORIES WHICH HAVING AVERAGE PROFIT WHICH IS GREATER THAN 50

In [36]:
query = """
SELECT Category,
AVG(Profit) AS Avg_Profit
FROM sales
GROUP BY Category
HAVING AVG(Profit) > 50
"""

pd.read_sql(query, conn)

          Category  Avg_Profit
0        Furniture  262.526803
1  Office Supplies  277.835934
2       Technology  242.464894

HERE WE CAN SEE STATES WHICH HAVING MORE THAN 100 ORDERS

In [37]:
query = """
SELECT State,
COUNT(*) AS Total_Orders
FROM sales
GROUP BY State
HAVING COUNT(*) > 100
ORDER BY Total_Orders DESC
"""

pd.read_sql(query, conn)

        State  Total_Orders
0  California           211
1  Washington           201
2     Florida           199
3       Texas           195
4    New York           194

HERE WE CAN SEE CUSTOMERS SEGMENT WITH SALES WHICH HAVING GRAETER THAN 500000

In [38]:
query = """
SELECT Segment,
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Segment
HAVING SUM(Sales) > 500000
"""

pd.read_sql(query, conn)

       Segment  Total_Sales
0     Consumer    861971.93
1    Corporate    927421.75
2  Home Office    796409.17

HERE CATEGORY WISE SALES AND PROFITS WHICH IS GREATER THAN 10000

In [39]:
query = """
SELECT Category,
SUM(Sales) AS Total_Sales,
SUM(Profit) AS Total_Profit
FROM sales
GROUP BY Category
HAVING SUM(Profit) > 10000
"""

pd.read_sql(query, conn)

          Category  Total_Sales  Total_Profit
0        Furniture    809125.55      83746.05
1  Office Supplies    776296.76      84739.96
2       Technology   1000380.54      91166.80

# JOINS

Q. WHY WE USE JOIN

A. IN REAL DATABASES, DATA IS USUALLY STORED IN MULTIPLE TABLES

HERE WE ARE USING SAMPLESUPERSTORE DATASET WE ONLY HAVE ONE TABLE FOR JOIN WE NEED 2 TABLES SO LET'S CREATE 2 TABLES

HERE WE CREATED TABLE 1: CUSTOMERS TABLE

In [40]:
customers = df[['Customer ID', 'Customer Name', 'Segment']].drop_duplicates()

customers.to_sql('customers', conn, if_exists='replace', index=False)

1000

HERE WE CREATED TABLE 2: ORDERS TABLE

In [41]:
orders = df[['Order ID', 'Customer ID', 'Sales', 'Profit', 'Category']]

orders.to_sql('orders', conn, if_exists='replace', index=False)

1000

# INNER JOIN

HERE IT SHOWS MATCHING RECORDS FROM BOTH TABLE1 AND TABLE2 TABLES

HERE LET ME EXPLAIN SOMETHING WHICH WE NEED TO UNDERSTAND

c --> CUSTOMERS TABLE ALIES

o --> ORDERS TABLE ALIES

IT JUST SHOWS MATCHING ROWS AND CUSTOMER ID WHICH IS SIMILAR TO EACH OTHER

In [42]:
query = """
SELECT
c.[Customer Name],
c.Segment,
o.Sales,
o.Profit
FROM customers c
INNER JOIN orders o
ON c.[Customer ID] = o.[Customer ID]
LIMIT 10
"""

pd.read_sql(query, conn)

  Customer Name      Segment    Sales  Profit
0    Customer 1     Consumer   714.90  103.84
1    Customer 2     Consumer  3585.78 -142.64
2    Customer 3     Consumer   481.87  131.91
3    Customer 4  Home Office  4429.55  896.04
4    Customer 5  Home Office  2277.98   79.94
5    Customer 6     Consumer  1909.69  367.25
6    Customer 7     Consumer  1587.10  463.98
7    Customer 8  Home Office  2153.60   66.76
8    Customer 9  Home Office  3964.56  168.03
9   Customer 10  Home Office   575.53   44.24

# LEFT JOIN

IT SHOWS ALL CUSTOMERS, EVEN IF THEY HAVE NO ORDERS

In [43]:
query = """
SELECT
c.[Customer Name],
c.Segment,
o.Sales
FROM customers c
LEFT JOIN orders o
ON c.[Customer ID] = o.[Customer ID]
LIMIT 10
"""

pd.read_sql(query, conn)

  Customer Name      Segment    Sales
0    Customer 1     Consumer   714.90
1    Customer 2     Consumer  3585.78
2    Customer 3     Consumer   481.87
3    Customer 4  Home Office  4429.55
4    Customer 5  Home Office  2277.98
5    Customer 6     Consumer  1909.69
6    Customer 7     Consumer  1587.10
7    Customer 8  Home Office  2153.60
8    Customer 9  Home Office  3964.56
9   Customer 10  Home Office   575.53

# RIGHT JOIN

HERE WE NEED TO KNOW ABOUT SQLITE DOESN'T SUPPORT RIGHT JOIN DIRECTLY , WE USE THIS CODE

In [44]:
query = """
SELECT
c.[Customer Name],
o.Sales
FROM orders o
LEFT JOIN customers c
ON o.[Customer ID] = c.[Customer ID]
LIMIT 10
"""

pd.read_sql(query, conn)

  Customer Name    Sales
0    Customer 1   714.90
1    Customer 2  3585.78
2    Customer 3   481.87
3    Customer 4  4429.55
4    Customer 5  2277.98
5    Customer 6  1909.69
6    Customer 7  1587.10
7    Customer 8  2153.60
8    Customer 9  3964.56
9   Customer 10   575.53

# TOTAL SALES BY CUSTOMER

In [45]:
query = """
SELECT
c.[Customer Name],
SUM(o.Sales) AS Total_Sales
FROM customers c
INNER JOIN orders o
ON c.[Customer ID] = o.[Customer ID]
GROUP BY c.[Customer Name]
ORDER BY Total_Sales DESC
LIMIT 10
"""

pd.read_sql(query, conn)

  Customer Name  Total_Sales
0  Customer 695      4997.24
1  Customer 495      4994.78
2  Customer 279      4987.40
3  Customer 932      4986.21
4  Customer 244      4985.86
5  Customer 404      4985.45
6  Customer 475      4985.14
7  Customer 477      4981.99
8  Customer 921      4981.01
9  Customer 283      4961.89

# TOTAL PROFITS BY CUSTOMER

In [46]:
query = """
SELECT
c.[Customer Name],
SUM(o.Profit) AS Total_Profit
FROM customers c
INNER JOIN orders o
ON c.[Customer ID] = o.[Customer ID]
GROUP BY c.[Customer Name]
ORDER BY Total_Profit DESC
LIMIT 10
"""

pd.read_sql(query, conn)

  Customer Name  Total_Profit
0  Customer 283       1704.88
1  Customer 657       1661.89
2  Customer 711       1641.43
3  Customer 366       1636.04
4  Customer 996       1634.83
5  Customer 565       1622.25
6  Customer 751       1571.35
7  Customer 507       1554.92
8  Customer 642       1541.49
9  Customer 596       1532.16

# ADVANCED SQL

# SUBQUERY

SUBQUERY IS A QUERY INSIDE ANOTHER QUERY

In [47]:
# HERE WE FIND ORDERS ABOVE AVERAGE SALES
query="""
SELECT *
FROM sales
WHERE Sales >
(
    SELECT AVG(Sales)
    FROM sales
    )
    LIMIT 10
    """
pd.read_sql(query,conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,2,CA-2024-10002,2024-04-29,2024-05-04,First Class,CUST-1002,Customer 2,Consumer,United States,Seattle,...,30926,South,PROD-2002,Technology,Phones,Phones Product 2,3585.78,9,0.3,-142.64
1,4,CA-2024-10004,2024-07-12,2024-07-13,Standard Class,CUST-1004,Customer 4,Home Office,United States,Tacoma,...,39871,Central,PROD-2004,Technology,Copiers,Copiers Product 4,4429.55,6,0.1,896.04
2,9,CA-2024-10009,2024-01-25,2024-02-01,Same Day,CUST-1009,Customer 9,Home Office,United States,Los Angeles,...,42953,East,PROD-2009,Technology,Phones,Phones Product 9,3964.56,7,0.0,168.03
3,11,CA-2024-10011,2024-11-16,2024-11-19,Same Day,CUST-1011,Customer 11,Consumer,United States,Seattle,...,24662,Central,PROD-2011,Furniture,Tables,Tables Product 11,3817.30,9,0.0,570.58
4,13,CA-2024-10013,2024-10-08,2024-10-10,First Class,CUST-1013,Customer 13,Corporate,United States,Buffalo,...,77839,South,PROD-2013,Furniture,Bookcases,Bookcases Product 13,3781.22,4,0.2,187.16
5,14,CA-2024-10014,2024-03-02,2024-03-04,Standard Class,CUST-1014,Customer 14,Consumer,United States,Houston,...,18834,East,PROD-2014,Office Supplies,Binders,Binders Product 14,2949.78,4,0.1,-431.86
6,21,CA-2024-10021,2024-10-23,2024-10-28,Second Class,CUST-1021,Customer 21,Home Office,United States,Los Angeles,...,51180,West,PROD-2021,Office Supplies,Storage,Storage Product 21,2926.69,9,0.2,928.79
7,22,CA-2024-10022,2024-05-15,2024-05-19,Standard Class,CUST-1022,Customer 22,Consumer,United States,Dallas,...,80468,West,PROD-2022,Office Supplies,Paper,Paper Product 22,4646.51,2,0.0,367.74
8,24,CA-2024-10024,2024-12-07,2024-12-14,Standard Class,CUST-1024,Customer 24,Home Office,United States,Tacoma,...,82512,West,PROD-2024,Technology,Phones,Phones Product 24,4695.87,3,0.2,-433.36
9,26,CA-2024-10026,2024-05-21,2024-05-22,Same Day,CUST-1026,Customer 26,Home Office,United States,San Diego,...,11267,East,PROD-2026,Furniture,Bookcases,Bookcases Product 26,4899.39,3,0.3,616.54

In [48]:
# HERE WE FIND ORDERS ABOVE AVERAGE profit
query="""
SELECT *
FROM sales
WHERE Profit >
(
    SELECT AVG(Profit)
    FROM sales
    )
    LIMIT 10
    """
pd.read_sql(query,conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,4,CA-2024-10004,2024-07-12,2024-07-13,Standard Class,CUST-1004,Customer 4,Home Office,United States,Tacoma,...,39871,Central,PROD-2004,Technology,Copiers,Copiers Product 4,4429.55,6,0.1,896.04
1,6,CA-2024-10006,2024-11-07,2024-11-13,Standard Class,CUST-1006,Customer 6,Consumer,United States,Houston,...,14207,Central,PROD-2006,Furniture,Tables,Tables Product 6,1909.69,9,0.1,367.25
2,7,CA-2024-10007,2024-07-24,2024-07-27,Same Day,CUST-1007,Customer 7,Consumer,United States,Los Angeles,...,44718,West,PROD-2007,Technology,Copiers,Copiers Product 7,1587.10,8,0.3,463.98
3,11,CA-2024-10011,2024-11-16,2024-11-19,Same Day,CUST-1011,Customer 11,Consumer,United States,Seattle,...,24662,Central,PROD-2011,Furniture,Tables,Tables Product 11,3817.30,9,0.0,570.58
4,15,CA-2024-10015,2024-06-18,2024-06-19,Same Day,CUST-1015,Customer 15,Consumer,United States,Seattle,...,71993,South,PROD-2015,Office Supplies,Storage,Storage Product 15,2437.36,9,0.1,515.93
5,19,CA-2024-10019,2024-05-26,2024-05-30,Standard Class,CUST-1019,Customer 19,Consumer,United States,Tacoma,...,86569,South,PROD-2019,Furniture,Chairs,Chairs Product 19,1497.60,1,0.0,335.44
6,21,CA-2024-10021,2024-10-23,2024-10-28,Second Class,CUST-1021,Customer 21,Home Office,United States,Los Angeles,...,51180,West,PROD-2021,Office Supplies,Storage,Storage Product 21,2926.69,9,0.2,928.79
7,22,CA-2024-10022,2024-05-15,2024-05-19,Standard Class,CUST-1022,Customer 22,Consumer,United States,Dallas,...,80468,West,PROD-2022,Office Supplies,Paper,Paper Product 22,4646.51,2,0.0,367.74
8,23,CA-2024-10023,2024-09-16,2024-09-19,First Class,CUST-1023,Customer 23,Home Office,United States,Dallas,...,95717,East,PROD-2023,Furniture,Chairs,Chairs Product 23,1860.24,3,0.3,496.45
9,26,CA-2024-10026,2024-05-21,2024-05-22,Same Day,CUST-1026,Customer 26,Home Office,United States,San Diego,...,11267,East,PROD-2026,Furniture,Bookcases,Bookcases Product 26,4899.39,3,0.3,616.54

In [49]:
# HERE WE FIND PRODUCTS WITH HIGHEST PROFIT
query="""
SELECT *
FROM sales
WHERE Profit >
(
    SELECT MAX(Profit)
    FROM sales
    )
    """
pd.read_sql(query,conn)

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

In [50]:
# HERE WE FIND CUSTOMERS WHOSE SALES ARE ABOVE AVERAGE
query="""
SELECT *
FROM sales
WHERE Sales >
(
    SELECT AVG(Sales)
    FROM sales
    )
    ORDER BY Sales DESC
    LIMIT 10
    """
pd.read_sql(query,conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,695,CA-2024-10695,2024-11-05,2024-11-09,Same Day,CUST-1695,Customer 695,Home Office,United States,Buffalo,...,17502,Central,PROD-2695,Technology,Accessories,Accessories Product 695,4997.24,4,0.2,912.19
1,495,CA-2024-10495,2024-04-21,2024-04-23,Second Class,CUST-1495,Customer 495,Home Office,United States,Buffalo,...,70199,East,PROD-2495,Furniture,Bookcases,Bookcases Product 495,4994.78,1,0.3,921.63
2,279,CA-2024-10279,2024-12-04,2024-12-07,Standard Class,CUST-1279,Customer 279,Home Office,United States,Houston,...,84978,West,PROD-2279,Technology,Accessories,Accessories Product 279,4987.40,5,0.3,260.84
3,932,CA-2024-10932,2024-11-16,2024-11-17,Standard Class,CUST-1932,Customer 932,Consumer,United States,Seattle,...,58435,East,PROD-2932,Technology,Accessories,Accessories Product 932,4986.21,8,0.3,-314.70
4,244,CA-2024-10244,2024-07-09,2024-07-15,Standard Class,CUST-1244,Customer 244,Corporate,United States,San Diego,...,26059,East,PROD-2244,Furniture,Chairs,Chairs Product 244,4985.86,4,0.3,1269.65
5,404,CA-2024-10404,2024-09-06,2024-09-10,First Class,CUST-1404,Customer 404,Corporate,United States,Seattle,...,52390,East,PROD-2404,Technology,Copiers,Copiers Product 404,4985.45,9,0.1,-143.79
6,475,CA-2024-10475,2024-06-19,2024-06-25,First Class,CUST-1475,Customer 475,Consumer,United States,Buffalo,...,70245,Central,PROD-2475,Furniture,Bookcases,Bookcases Product 475,4985.14,2,0.2,584.82
7,477,CA-2024-10477,2024-04-07,2024-04-09,First Class,CUST-1477,Customer 477,Corporate,United States,Los Angeles,...,79984,South,PROD-2477,Furniture,Bookcases,Bookcases Product 477,4981.99,4,0.3,221.12
8,921,CA-2024-10921,2024-08-29,2024-09-02,Same Day,CUST-1921,Customer 921,Consumer,United States,Dallas,...,51640,South,PROD-2921,Technology,Copiers,Copiers Product 921,4981.01,3,0.1,558.82
9,283,CA-2024-10283,2024-09-28,2024-10-01,Same Day,CUST-1283,Customer 283,Consumer,United States,Miami,...,51469,West,PROD-2283,Furniture,Chairs,Chairs Product 283,4961.89,6,0.3,1704.88

In [51]:
# HERE WE FINDED STATES HAVING SALES GREATER THAN AVERAGE STATE SALES
query="""
SELECT State,
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY State
HAVING SUM(Sales) >
(
    SELECT AVG(Sales)
    FROM sales
    )
    """
pd.read_sql(query,conn)

        State  Total_Sales
0  California    564487.72
1     Florida    517151.60
2    New York    499426.19
3       Texas    477890.35
4  Washington    526846.99

In [52]:
# HERE WE FINDED STATES HAVING PROFIT GREATER THAN AVERAGE STATE PROFIT
query="""
SELECT State,
SUM(Profit) AS Total_Profit
FROM sales
GROUP BY State
HAVING SUM(Profit) >
(
    SELECT AVG(Profit)
    FROM sales
    )
    """
pd.read_sql(query,conn)

        State  Total_Profit
0  California      51912.27
1     Florida      54694.08
2    New York      47135.65
3       Texas      55224.27
4  Washington      50686.54

# CTE(WITH CLAUSE)

A CTE (COMMON TABLE EXPRESSION) CREATES A TEMPORARY RESULT SET THAT CAN BE USED IN THE MAIN QUERY

In [53]:
# HERE WE FIND CATEGORY SALES ANALYSIS
query = """
WITH CategorySales AS
(
    SELECT Category,
           SUM(Sales) AS Total_Sales
    FROM sales
    GROUP BY Category
)

SELECT *
FROM CategorySales
ORDER BY Total_Sales DESC
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0       Technology   1000380.54
1        Furniture    809125.55
2  Office Supplies    776296.76

In [54]:
# HERE WE FIND CATEGORY PROFIT ANALYSIS
query = """
WITH CategoryProfit AS
(
    SELECT Category,
           SUM(Profit) AS Total_Profit
    FROM sales
    GROUP BY Category
)

SELECT *
FROM CategoryProfit
ORDER BY Total_Profit DESC
"""

pd.read_sql(query, conn)

          Category  Total_Profit
0       Technology      91166.80
1  Office Supplies      84739.96
2        Furniture      83746.05

In [55]:
# HERE WE FIND STATE SALES ANALYSIS
query = """
WITH StateSales AS
(
    SELECT State,
           SUM(Sales) AS Total_Sales
    FROM sales
    GROUP BY State
)

SELECT *
FROM StateSales
WHERE Total_Sales > 50000
ORDER BY Total_Sales DESC
"""

pd.read_sql(query, conn)

        State  Total_Sales
0  California    564487.72
1  Washington    526846.99
2     Florida    517151.60
3    New York    499426.19
4       Texas    477890.35

In [56]:
# HERE WE FIND STATE PROFIT ANALYSIS
query = """
WITH StateProfit AS
(
    SELECT State,
           SUM(Profit) AS Total_Profit
    FROM sales
    GROUP BY State
)

SELECT *
FROM StateProfit
ORDER BY Total_Profit DESC
"""

pd.read_sql(query, conn)

        State  Total_Profit
0       Texas      55224.27
1     Florida      54694.08
2  California      51912.27
3  Washington      50686.54
4    New York      47135.65

In [57]:
# HERE WE FIND TOP 10 CUSTOMERS SALES USING CTE
query = """
WITH CustomerSales AS
(
    SELECT [Customer Name],
           SUM(Sales) AS Total_Sales
    FROM sales
    GROUP BY [Customer Name]
)

SELECT *
FROM CustomerSales
ORDER BY Total_Sales DESC
LIMIT 10
"""

pd.read_sql(query, conn)

  Customer Name  Total_Sales
0  Customer 695      4997.24
1  Customer 495      4994.78
2  Customer 279      4987.40
3  Customer 932      4986.21
4  Customer 244      4985.86
5  Customer 404      4985.45
6  Customer 475      4985.14
7  Customer 477      4981.99
8  Customer 921      4981.01
9  Customer 283      4961.89

In [58]:
# HERE WE FIND TOP 10 CUSTOMERS PROFIT USING CTE
query = """
WITH CustomerProfit AS
(
    SELECT [Customer Name],
           SUM(Profit) AS Total_Profit
    FROM sales
    GROUP BY [Customer Name]
)

SELECT *
FROM CustomerProfit
ORDER BY Total_Profit DESC
LIMIT 10
"""

pd.read_sql(query, conn)

  Customer Name  Total_Profit
0  Customer 283       1704.88
1  Customer 657       1661.89
2  Customer 711       1641.43
3  Customer 366       1636.04
4  Customer 996       1634.83
5  Customer 565       1622.25
6  Customer 751       1571.35
7  Customer 507       1554.92
8  Customer 642       1541.49
9  Customer 596       1532.16

In [59]:
# HERE WE FIND CATEGORY SALES AND PROFIT TOGETHER
query = """
WITH CategoryStats AS
(
    SELECT Category,
           SUM(Sales) AS Total_Sales,
           SUM(Profit) AS Total_Profit
    FROM sales
    GROUP BY Category
)

SELECT *
FROM CategoryStats
ORDER BY Total_Profit DESC
"""

pd.read_sql(query, conn)

          Category  Total_Sales  Total_Profit
0       Technology   1000380.54      91166.80
1  Office Supplies    776296.76      84739.96
2        Furniture    809125.55      83746.05

# ROW()

WHY WE USE ROW_NUMBER ?

WE USE ROW_NUMBER BECAUSE IT GIVES A UNIQUE NUMBER TO EACH ROW

In [60]:
# HERE IT SHOWS TOP SALES RANKING
query = """
SELECT
[Customer Name],
Sales,
ROW_NUMBER() OVER(
ORDER BY Sales DESC
) AS Row_Num
FROM sales
LIMIT 10
"""

pd.read_sql(query, conn)

  Customer Name    Sales  Row_Num
0  Customer 695  4997.24        1
1  Customer 495  4994.78        2
2  Customer 279  4987.40        3
3  Customer 932  4986.21        4
4  Customer 244  4985.86        5
5  Customer 404  4985.45        6
6  Customer 475  4985.14        7
7  Customer 477  4981.99        8
8  Customer 921  4981.01        9
9  Customer 283  4961.89       10

In [61]:
# HERE IT SHOWS TOP PROFITS RANKING
query = """
SELECT
[Customer Name],
Profit,
ROW_NUMBER() OVER(
ORDER BY Profit DESC
) AS Row_Num
FROM sales
LIMIT 10
"""

pd.read_sql(query, conn)

  Customer Name   Profit  Row_Num
0  Customer 283  1704.88        1
1  Customer 657  1661.89        2
2  Customer 711  1641.43        3
3  Customer 366  1636.04        4
4  Customer 996  1634.83        5
5  Customer 565  1622.25        6
6  Customer 751  1571.35        7
7  Customer 507  1554.92        8
8  Customer 642  1541.49        9
9  Customer 596  1532.16       10

HERE WHY WE USE PARTITION BY BECAUSE IT CREATES SEPERATES RANKINGS INSIDE EACH CETEGORY

FOR EX : TECHNOLOGY IT DECLARES RANK 1, RANK 2,......

In [62]:
# HERE WE CAN SEE ROW NUM WITHIN EACH CATEGORY
query = """
SELECT
Category,
[Customer Name],
Sales,
ROW_NUMBER() OVER(
PARTITION BY Category
ORDER BY Sales DESC
) AS Category_Rank
FROM sales
LIMIT 20
"""

pd.read_sql(query, conn)

     Category Customer Name    Sales  Category_Rank
0   Furniture  Customer 495  4994.78              1
1   Furniture  Customer 244  4985.86              2
2   Furniture  Customer 475  4985.14              3
3   Furniture  Customer 477  4981.99              4
4   Furniture  Customer 283  4961.89              5
5   Furniture  Customer 626  4921.63              6
6   Furniture  Customer 711  4901.78              7
7   Furniture   Customer 26  4899.39              8
8   Furniture  Customer 657  4886.67              9
9   Furniture  Customer 320  4858.71             10
10  Furniture  Customer 132  4838.45             11
11  Furniture  Customer 501  4792.12             12
12  Furniture  Customer 809  4791.33             13
13  Furniture  Customer 743  4742.67             14
14  Furniture   Customer 84  4732.38             15
15  Furniture  Customer 533  4713.17             16
16  Furniture  Customer 897  4710.19             17
17  Furniture  Customer 176  4687.06             18
18  Furniture  Customer 565  4656.70             19
19  Furniture  Customer 305  4652.48             20

In [63]:
# HERE WE CAN SEE ROW NUM WITHIN EACH CATEGORY
query = """
SELECT
Category,
[Customer Name],
Profit,
ROW_NUMBER() OVER(
PARTITION BY Category
ORDER BY Profit DESC
) AS Category_Rank
FROM sales
LIMIT 20
"""

pd.read_sql(query, conn)

     Category Customer Name   Profit  Category_Rank
0   Furniture  Customer 283  1704.88              1
1   Furniture  Customer 657  1661.89              2
2   Furniture  Customer 711  1641.43              3
3   Furniture  Customer 565  1622.25              4
4   Furniture  Customer 507  1554.92              5
5   Furniture  Customer 176  1439.96              6
6   Furniture  Customer 626  1402.46              7
7   Furniture  Customer 380  1379.52              8
8   Furniture   Customer 83  1360.79              9
9   Furniture  Customer 400  1336.69             10
10  Furniture  Customer 630  1329.43             11
11  Furniture  Customer 867  1292.89             12
12  Furniture  Customer 770  1289.92             13
13  Furniture  Customer 444  1278.93             14
14  Furniture  Customer 244  1269.65             15
15  Furniture  Customer 707  1258.57             16
16  Furniture  Customer 998  1180.13             17
17  Furniture  Customer 608  1154.40             18
18  Furniture  Customer 855  1134.67             19
19  Furniture  Customer 556  1120.82             20

# RANK()

WHY WE USE RANK() ?

WE USE RANKS BACAUSE IT RANKS RECORDS BUT HANDLES TIES

In [64]:
query = """
SELECT
[Customer Name],
Sales,
RANK() OVER(
ORDER BY Sales DESC
) AS Sales_Rank
FROM sales
LIMIT 10
"""

pd.read_sql(query, conn)

  Customer Name    Sales  Sales_Rank
0  Customer 695  4997.24           1
1  Customer 495  4994.78           2
2  Customer 279  4987.40           3
3  Customer 932  4986.21           4
4  Customer 244  4985.86           5
5  Customer 404  4985.45           6
6  Customer 475  4985.14           7
7  Customer 477  4981.99           8
8  Customer 921  4981.01           9
9  Customer 283  4961.89          10

In [65]:
query = """
SELECT
[Customer Name],
Profit,
RANK() OVER(
ORDER BY Profit DESC
) AS Profit_Rank
FROM sales
LIMIT 10
"""

pd.read_sql(query, conn)

  Customer Name   Profit  Profit_Rank
0  Customer 283  1704.88            1
1  Customer 657  1661.89            2
2  Customer 711  1641.43            3
3  Customer 366  1636.04            4
4  Customer 996  1634.83            5
5  Customer 565  1622.25            6
6  Customer 751  1571.35            7
7  Customer 507  1554.92            8
8  Customer 642  1541.49            9
9  Customer 596  1532.16           10

# DENSE RANK( )

IT IS SIMILAR TO RANK BUT DOESN'T SKIP NUMBERS

In [66]:
# HERE WE CAN SEE DENSE RANK FOR SALES
query = """
SELECT
[Customer Name],
Sales,
DENSE_RANK() OVER(
ORDER BY Sales DESC
) AS Dense_Rank
FROM sales
LIMIT 10
"""

pd.read_sql(query, conn)

  Customer Name    Sales  Dense_Rank
0  Customer 695  4997.24           1
1  Customer 495  4994.78           2
2  Customer 279  4987.40           3
3  Customer 932  4986.21           4
4  Customer 244  4985.86           5
5  Customer 404  4985.45           6
6  Customer 475  4985.14           7
7  Customer 477  4981.99           8
8  Customer 921  4981.01           9
9  Customer 283  4961.89          10

In [67]:
# HERE WE CAN SEE DENSE RANK FOR PROFITS
query = """
SELECT
[Customer Name],
Profit,
DENSE_RANK() OVER(
ORDER BY Profit DESC
) AS Dense_Rank
FROM sales
LIMIT 10
"""

pd.read_sql(query, conn)

  Customer Name   Profit  Dense_Rank
0  Customer 283  1704.88           1
1  Customer 657  1661.89           2
2  Customer 711  1641.43           3
3  Customer 366  1636.04           4
4  Customer 996  1634.83           5
5  Customer 565  1622.25           6
6  Customer 751  1571.35           7
7  Customer 507  1554.92           8
8  Customer 642  1541.49           9
9  Customer 596  1532.16          10

# LAG( )

WHY WE USE LAG( )?

WE USE LAG( ) BECAUSE IT ACCESSES THE PREVIOUS ROW'S VALUE

In [68]:
# HERE WE CAN SEE PREVIOUS SALES VALUE 
query = """
SELECT
[Order Date],
Sales,
LAG(Sales,1) OVER(
ORDER BY [Order Date]
) AS Previous_Sales
FROM sales
LIMIT 10
"""

pd.read_sql(query, conn)

   Order Date    Sales  Previous_Sales
0  2024-01-01  3692.59             NaN
1  2024-01-01   753.94         3692.59
2  2024-01-02  3009.07          753.94
3  2024-01-03  3211.38         3009.07
4  2024-01-03  4448.15         3211.38
5  2024-01-03  2396.06         4448.15
6  2024-01-03  4042.21         2396.06
7  2024-01-04  2656.50         4042.21
8  2024-01-04  2196.79         2656.50
9  2024-01-04  2621.23         2196.79

In [69]:
# HERE WE CAN SEE PREVIOUS PROFIT VALUE 
query = """
SELECT
[Order Date],
Profit,
LAG(Profit,1) OVER(
ORDER BY [Order Date]
) AS Previous_Profit
FROM sales
LIMIT 10
"""

pd.read_sql(query, conn)

   Order Date   Profit  Previous_Profit
0  2024-01-01   210.55              NaN
1  2024-01-01   234.36           210.55
2  2024-01-02  -412.64           234.36
3  2024-01-03  -266.05          -412.64
4  2024-01-03  -617.22          -266.05
5  2024-01-03     3.35          -617.22
6  2024-01-03  1329.43             3.35
7  2024-01-04  -375.71          1329.43
8  2024-01-04   455.77          -375.71
9  2024-01-04   397.10           455.77

In [70]:
# HERE BY USING LAG WE CAN SEE SALES DIFFERENCE
query = """
SELECT
[Order Date],
Sales,
Sales -
LAG(Sales,1) OVER(
ORDER BY [Order Date]
) AS Sales_Difference
FROM sales
LIMIT 10
"""

pd.read_sql(query, conn)

   Order Date    Sales  Sales_Difference
0  2024-01-01  3692.59               NaN
1  2024-01-01   753.94          -2938.65
2  2024-01-02  3009.07           2255.13
3  2024-01-03  3211.38            202.31
4  2024-01-03  4448.15           1236.77
5  2024-01-03  2396.06          -2052.09
6  2024-01-03  4042.21           1646.15
7  2024-01-04  2656.50          -1385.71
8  2024-01-04  2196.79           -459.71
9  2024-01-04  2621.23            424.44

In [71]:
# HERE BY USING LAG WE CAN SEE PROFIT DIFFERENCE
query = """
SELECT
[Order Date],
Profit,
Profit -
LAG(Profit,1) OVER(
ORDER BY [Order Date]
) AS Profit_Difference
FROM sales
LIMIT 10
"""

pd.read_sql(query, conn)

   Order Date   Profit  Profit_Difference
0  2024-01-01   210.55                NaN
1  2024-01-01   234.36              23.81
2  2024-01-02  -412.64            -647.00
3  2024-01-03  -266.05             146.59
4  2024-01-03  -617.22            -351.17
5  2024-01-03     3.35             620.57
6  2024-01-03  1329.43            1326.08
7  2024-01-04  -375.71           -1705.14
8  2024-01-04   455.77             831.48
9  2024-01-04   397.10             -58.67

# LEAD( )

WHY WE USE LEAD( )?

WE USE LEAD BECAUSE IT ACCESSES THE NEXT ROW'S VALUE

In [72]:
# HERE WE CAN SEE NEXT SALES VALUE 
query = """
SELECT
[Order Date],
Sales,
LEAD(Sales,1) OVER(
ORDER BY [Order Date]
) AS Next_Sales
FROM sales
LIMIT 10
"""

pd.read_sql(query, conn)

   Order Date    Sales  Next_Sales
0  2024-01-01  3692.59      753.94
1  2024-01-01   753.94     3009.07
2  2024-01-02  3009.07     3211.38
3  2024-01-03  3211.38     4448.15
4  2024-01-03  4448.15     2396.06
5  2024-01-03  2396.06     4042.21
6  2024-01-03  4042.21     2656.50
7  2024-01-04  2656.50     2196.79
8  2024-01-04  2196.79     2621.23
9  2024-01-04  2621.23     4710.19

In [73]:
# HERE WE CAN SEE NEXT PROFIT VALUE 
query = """
SELECT
[Order Date],
Profit,
LEAD(Profit,1) OVER(
ORDER BY [Order Date]
) AS Next_Profit
FROM sales
LIMIT 10
"""

pd.read_sql(query, conn)

   Order Date   Profit  Next_Profit
0  2024-01-01   210.55       234.36
1  2024-01-01   234.36      -412.64
2  2024-01-02  -412.64      -266.05
3  2024-01-03  -266.05      -617.22
4  2024-01-03  -617.22         3.35
5  2024-01-03     3.35      1329.43
6  2024-01-03  1329.43      -375.71
7  2024-01-04  -375.71       455.77
8  2024-01-04   455.77       397.10
9  2024-01-04   397.10      1017.61

# CREATING VIEWS FOR REUSABLE QUERIES

Q. WHY WE USE VIEW?


A. A VIEW IS A VIRTUAL TABLE CREATED FROM THE RESULT OF A SQL QUERY. IT DOES'NT STORE DATA SEPERATELY

   BUT HELPS SIMPLIFY AND REUSE COMPLEX QUERIES

In [74]:
# HERE WE CREATED CATEGORY SALES VIEW 
query = """
CREATE VIEW Category_Sales_View AS
SELECT Category,
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Category
"""
conn.execute(query)

In [75]:
pd.read_sql("""
SELECT *
FROM Category_Sales_View
""",conn)

          Category  Total_Sales
0        Furniture    809125.55
1  Office Supplies    776296.76
2       Technology   1000380.54

In [76]:
conn.execute("DROP VIEW IF EXISTS Category_Profit_View")

In [77]:
# HERE WE CREATED CATEGORY PROFIT VIEW 
query = """
CREATE VIEW Category_Profit_View AS
SELECT Category,
SUM(Profit) AS Total_Profit
FROM sales
GROUP BY Category
"""
conn.execute(query)

In [78]:
pd.read_sql("""
SELECT *
FROM Category_Profit_View
""",conn)

          Category  Total_Profit
0        Furniture      83746.05
1  Office Supplies      84739.96
2       Technology      91166.80

In [79]:
conn.execute("DROP VIEW IF EXISTS State_Sales_View")

In [80]:
# HERE WE CREATED STATE SALES VIEW 
query = """
CREATE VIEW State_Sales_View AS
SELECT State,
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY State
"""
conn.execute(query)

In [81]:
pd.read_sql("""
SELECT *
FROM State_Sales_View DESC
""",conn)

        State  Total_Sales
0  California    564487.72
1     Florida    517151.60
2    New York    499426.19
3       Texas    477890.35
4  Washington    526846.99

In [82]:
conn.execute("DROP VIEW IF EXISTS State_Profit_View")

In [83]:
# HERE WE CREATED STATE PROFIT VIEW 
query = """
CREATE VIEW State_Profit_View AS
SELECT State,
SUM(Profit) AS Total_Profit
FROM sales
GROUP BY State
"""
conn.execute(query)

In [84]:
pd.read_sql("""
SELECT *
FROM State_Profit_View DESC
""",conn)

        State  Total_Profit
0  California      51912.27
1     Florida      54694.08
2    New York      47135.65
3       Texas      55224.27
4  Washington      50686.54

In [85]:
conn.execute("DROP VIEW IF EXISTS Customer_Sales_View")

In [86]:
# HERE WE CREATED CUSTOMER SALES VIEW
query = """
CREATE VIEW Customer_Sales_View AS
SELECT [Customer Name],
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY [Customer Name]
"""
conn.execute(query)

In [87]:
pd.read_sql("""
SELECT *
FROM Customer_Sales_View 
ORDER BY Total_Sales DESC
LIMIT 10
""",conn)

  Customer Name  Total_Sales
0  Customer 695      4997.24
1  Customer 495      4994.78
2  Customer 279      4987.40
3  Customer 932      4986.21
4  Customer 244      4985.86
5  Customer 404      4985.45
6  Customer 475      4985.14
7  Customer 477      4981.99
8  Customer 921      4981.01
9  Customer 283      4961.89

In [88]:
conn.execute("DROP VIEW IF EXISTS Customer_Profit_View")

In [89]:
# HERE WE CREATED CUSTOMER PROFIT VIEW
query = """
CREATE VIEW Customer_Profit_View AS
SELECT [Customer Name],
SUM(Profit) AS Total_Profit
FROM sales
GROUP BY [Customer Name]
"""
conn.execute(query)

In [90]:
pd.read_sql("""
SELECT *
FROM Customer_Profit_View 
ORDER BY Total_Profit DESC
LIMIT 10
""",conn)

  Customer Name  Total_Profit
0  Customer 283       1704.88
1  Customer 657       1661.89
2  Customer 711       1641.43
3  Customer 366       1636.04
4  Customer 996       1634.83
5  Customer 565       1622.25
6  Customer 751       1571.35
7  Customer 507       1554.92
8  Customer 642       1541.49
9  Customer 596       1532.16

In [91]:
conn.execute("DROP VIEW IF EXISTS Sales_View")

In [92]:
# HERE WE CREATED TOP SALES ORDER VIEW
query = """
CREATE VIEW Sales_View AS
SELECT 
[Order Id],
[Customer Name],
Sales,
Profit
FROM sales
WHERE Sales > 500
"""
conn.execute(query)

In [93]:
pd.read_sql("""
SELECT *
FROM Sales_View
LIMIT 10
""",conn)

        Order ID Customer Name    Sales  Profit
0  CA-2024-10001    Customer 1   714.90  103.84
1  CA-2024-10002    Customer 2  3585.78 -142.64
2  CA-2024-10004    Customer 4  4429.55  896.04
3  CA-2024-10005    Customer 5  2277.98   79.94
4  CA-2024-10006    Customer 6  1909.69  367.25
5  CA-2024-10007    Customer 7  1587.10  463.98
6  CA-2024-10008    Customer 8  2153.60   66.76
7  CA-2024-10009    Customer 9  3964.56  168.03
8  CA-2024-10010   Customer 10   575.53   44.24
9  CA-2024-10011   Customer 11  3817.30  570.58

In [94]:
conn.execute("DROP VIEW IF EXISTS Profit_View")

In [95]:
# HERE WE CREATED TOP PROFIT ORDER VIEW
query = """
CREATE VIEW Profit_View AS
SELECT 
[Order Id],
[Customer Name],
Sales,
Profit
FROM sales
WHERE Profit > 500
"""
conn.execute(query)

In [96]:
pd.read_sql("""
SELECT *
FROM Profit_View
LIMIT 10
""",conn)

        Order ID Customer Name    Sales   Profit
0  CA-2024-10004    Customer 4  4429.55   896.04
1  CA-2024-10011   Customer 11  3817.30   570.58
2  CA-2024-10015   Customer 15  2437.36   515.93
3  CA-2024-10021   Customer 21  2926.69   928.79
4  CA-2024-10026   Customer 26  4899.39   616.54
5  CA-2024-10028   Customer 28  4869.71  1374.73
6  CA-2024-10029   Customer 29  3941.13  1127.49
7  CA-2024-10031   Customer 31  4387.65   615.56
8  CA-2024-10035   Customer 35  2221.96   548.53
9  CA-2024-10043   Customer 43  4904.00  1488.19

In [97]:
conn.execute("DROP VIEW IF EXISTS Category_Stats")

In [98]:
# HERE WE CREATED SALES AND PROFIT VIEW
query = """
CREATE VIEW Category_Stats AS
SELECT 
Category,
SUM(Sales) AS Total_Sales,
SUM(Profit) AS Total_Profit
FROM sales
GROUP BY Category
"""
conn.execute(query)

In [99]:
pd.read_sql("""
SELECT *
FROM Category_Stats
""",conn)

          Category  Total_Sales  Total_Profit
0        Furniture    809125.55      83746.05
1  Office Supplies    776296.76      84739.96
2       Technology   1000380.54      91166.80

SHOW ALL THE VIEWS

In [100]:
pd.read_sql(
"""
SELECT name
FROM sqlite_master
WHERE type='view'
""",
conn)

                   name
0   Category_Sales_View
1  Category_Profit_View
2      State_Sales_View
3     State_Profit_View
4   Customer_Sales_View
5  Customer_Profit_View
6            Sales_View
7           Profit_View
8        Category_Stats

DELETE A VIEW

In [101]:
conn.execute("""
DROP VIEW Category_Sales_View
""")

# PYTHON + SQL INTEGRATION

# LETS BUILD TOP 10 BUSSINESS QUESTION AND SOLVE WITH USING SQL

Q 1 . WHICH CATEGORY GENERATES THE HIGHEST SALES?

In [103]:
query= """
SELECT Category,
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Category
ORDER BY Total_Sales DESC
"""
pd.read_sql(query,conn)

          Category  Total_Sales
0       Technology   1000380.54
1        Furniture    809125.55
2  Office Supplies    776296.76

Q 2. WHICH CATEGORY HAVE HIGHEST PROFITS?

In [104]:
query= """
SELECT Category,
SUM(Profit) AS Total_Profit
FROM sales
GROUP BY Category
ORDER BY Total_Profit DESC
"""
pd.read_sql(query,conn)

          Category  Total_Profit
0       Technology      91166.80
1  Office Supplies      84739.96
2        Furniture      83746.05

Q 3. WHAT ARE THE TOP 10 CUSTOMERS BY SALES?

In [106]:
query= """
SELECT [Customer Name],
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY [Customer Name]
ORDER BY Total_Sales DESC
LIMIT 10
"""
pd.read_sql(query,conn)

  Customer Name  Total_Sales
0  Customer 695      4997.24
1  Customer 495      4994.78
2  Customer 279      4987.40
3  Customer 932      4986.21
4  Customer 244      4985.86
5  Customer 404      4985.45
6  Customer 475      4985.14
7  Customer 477      4981.99
8  Customer 921      4981.01
9  Customer 283      4961.89

Q 4. WHAT ARE THE TOP 5 PRODUCTS BY SALES?

In [107]:
query= """
SELECT [Product Name],
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY [Product Name]
ORDER BY Total_Sales DESC
LIMIT 5
"""
pd.read_sql(query,conn)

              Product Name  Total_Sales
0  Accessories Product 695      4997.24
1    Bookcases Product 495      4994.78
2  Accessories Product 279      4987.40
3  Accessories Product 932      4986.21
4       Chairs Product 244      4985.86

Q 5. WHICH STATES GENERATE THE HIGHEST REVENUE?

In [108]:
query= """
SELECT State,
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY State
ORDER BY Total_Sales DESC
LIMIT 10
"""
pd.read_sql(query,conn)

        State  Total_Sales
0  California    564487.72
1  Washington    526846.99
2     Florida    517151.60
3    New York    499426.19
4       Texas    477890.35

Q 6. WHICH STATE GENERATE THE HIGHEST PROFIT?

In [109]:
query= """
SELECT State,
SUM(Profit) AS Total_Profit
FROM sales
GROUP BY State
ORDER BY Total_Profit DESC
LIMIT 10
"""
pd.read_sql(query,conn)

        State  Total_Profit
0       Texas      55224.27
1     Florida      54694.08
2  California      51912.27
3  Washington      50686.54
4    New York      47135.65

Q 7. WHICH CUSTOMER SEGMENT HAS THE HIGHEST SALES?

In [111]:
query= """
SELECT Segment,
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Segment
ORDER BY Total_Sales DESC
"""
pd.read_sql(query,conn)

       Segment  Total_Sales
0    Corporate    927421.75
1     Consumer    861971.93
2  Home Office    796409.17

Q 8. WHICH PRODUCTS ARE CAUSING LOSSES?

In [113]:
query= """
SELECT [Product Name],
SUM(Profit) AS Total_Profit
FROM sales
GROUP BY [Product Name]
HAVING SUM(Profit) < 0
ORDER BY Total_Profit ASC
LIMIT 10
"""
pd.read_sql(query,conn)

              Product Name  Total_Profit
0  Accessories Product 374       -688.75
1        Paper Product 313       -686.64
2    Bookcases Product 715       -661.56
3    Bookcases Product 236       -661.27
4       Chairs Product 483       -644.19
5       Phones Product 166       -626.97
6        Paper Product 474       -626.52
7       Tables Product 823       -621.16
8        Paper Product 440       -617.22
9       Binders Product 86       -587.25

Q 9. MONTHLY SALES TREND?

In [114]:
query = """
SELECT strftime('%Y-%m',[Order Date]) AS Year,
strftime('%m',[Order Date]) AS Month,
SUM(Sales) AS Monthly_Sales
FROM sales
GROUP BY Year, Month
ORDER BY Year, Month
"""

pd.read_sql(query, conn)

       Year Month  Monthly_Sales
0   2024-01    01      191543.40
1   2024-02    02      195993.48
2   2024-03    03      212208.07
3   2024-04    04      225956.35
4   2024-05    05      208845.66
5   2024-06    06      256785.81
6   2024-07    07      199068.33
7   2024-08    08      271185.44
8   2024-09    09      195633.30
9   2024-10    10      244208.88
10  2024-11    11      177870.76
11  2024-12    12      206503.37

Q 10. WHICH CUSTOMERS ARE HIGH,MEDIUM,AND LOW SPENDERS?

In [115]:
query = """
SELECT
[Customer Name],
SUM(Sales) AS Total_Spend,
CASE
    WHEN SUM(Sales) >= 5000 THEN 'High Spender'
    WHEN SUM(Sales) >= 2000 THEN 'Medium Spender'
    ELSE 'Low Spender'
END AS Customer_Segment
FROM sales
GROUP BY [Customer Name]
ORDER BY Total_Spend DESC
"""

pd.read_sql(query, conn)

    Customer Name  Total_Spend Customer_Segment
0    Customer 695      4997.24   Medium Spender
1    Customer 495      4994.78   Medium Spender
2    Customer 279      4987.40   Medium Spender
3    Customer 932      4986.21   Medium Spender
4    Customer 244      4985.86   Medium Spender
..            ...          ...              ...
995  Customer 790        38.31      Low Spender
996  Customer 697        35.58      Low Spender
997  Customer 558        35.32      Low Spender
998  Customer 690        27.86      Low Spender
999  Customer 473        24.32      Low Spender

[1000 rows x 3 columns]

In [117]:
import sqlite3
import pandas as pd

# Database Connection Function
def connect_db(db_name="superstore.db"):
    return sqlite3.connect(db_name)

# Execute SELECT Queries
def run_query(query):
    conn = connect_db()
    result = pd.read_sql(query, conn)
    conn.close()
    return result

In [118]:
query= """
SELECT Category,
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Category
"""
run_query(query)

          Category  Total_Sales
0        Furniture    809125.55
1  Office Supplies    776296.76
2       Technology   1000380.54